#name: Deploy
#on:
#  push:
#  pull_request:
#jobs:
#  tests:
#    runs-on: ubuntu-latest
#    name: Build & Deploy Assets
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Setup SSH
#        run: |
#          mkdir -p ~/.ssh/
#          printf "%s\n" "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
#          printf "%s\n" "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
#          chmod 600 ~/.ssh/id_rsa
#          chmod 644 ~/.ssh/id_rsa.pub
#          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts 2>/dev/null || true
#
#      - name: Test SSH Connection
#        run: |
#          ssh -o StrictHostKeyChecking=no syncflux@${{ secrets.SERVER_IP }} "echo 'SSH Connection Successful'"
#
#      - name: Deploy
#        run: |
#          ssh syncflux@${{ secrets.SERVER_IP }} 'bash -s' < ${{ github.workspace }}/.github/workflows/deploy.sh
